version: '3.8'

services:
  # Backend Service (Express.js + Python)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: terrahost-backend
    ports:
      - "${BACKEND_EXTERNAL_PORT:-3501}:${BACKEND_PORT:-8000}"
    environment:
      # Server Configuration
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${BACKEND_PORT:-8000}
      
      # Database Configuration
      - DB_HOST=${DB_HOST:-localhost}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-terrahost}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      
      # Database Pool Configuration
      - DB_POOL_MIN=${DB_POOL_MIN:-2}
      - DB_POOL_MAX=${DB_POOL_MAX:-10}
      - DB_POOL_IDLE_TIMEOUT=${DB_POOL_IDLE_TIMEOUT:-30000}
      
      # JWT Configuration
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-change-this-in-production}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-7d}
      
      # File Upload Configuration
      - UPLOAD_DIR=${UPLOAD_DIR:-./uploads}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-500MB}
      
      # Nextcloud Configuration
      - NEXTCLOUD_URL=${NEXTCLOUD_URL:-http://localhost:8080}
      - NEXTCLOUD_USERNAME=${NEXTCLOUD_USERNAME:-admin}
      - NEXTCLOUD_PASSWORD=${NEXTCLOUD_PASSWORD:-password}
      
      # Python Configuration
      - PYTHONPATH=/app/scripts
      - GDAL_DATA=/usr/share/gdal
      - PROJ_LIB=/usr/share/proj
    volumes:
      - ./backend/scripts:/app/scripts:ro
      - terrahost-temp:/app/temp
    networks:
      - terrahost-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Service (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8000}
        - NODE_ENV=${NODE_ENV:-production}
    container_name: terrahost-frontend
    ports:
      - "${FRONTEND_EXTERNAL_PORT:-3500}:${FRONTEND_PORT:-3000}"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8000}
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - terrahost-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  terrahost-network:
    driver: bridge

volumes:
  terrahost-temp:
    driver: local