version: '3.8'

services:
  # Backend Service (Express.js)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: terrahost-backend
    ports:
      - "3501:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
      - HOST=0.0.0.0
    networks:
      - terrahost-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Service (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: terrahost-frontend
    ports:
      - "3500:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - terrahost-network
    restart: unless-stopped

networks:
  terrahost-network:
    driver: bridge